### ISSUE TITLE
Question: How to rerun from a particular analysis step?

### ISSUE THREAD

**Issue by biocyberman** [NationalGenomicsInfrastructure/piper#56]
Piper lays out 8 analysis steps. When the analysis got to step 07, I found out there was something wrong in the step  05_processed_alignments (BaseRecalibrator). So, I deleted folders from 02_... to 08_... in order to rerun everything except the 01_raw_alignments step. However, when running piper, it seems to restart the raw alignment step also. How do I get this done, and any particular step?

Thanks
Vang

**Comment by johandahlberg** [comment]
This is related to the bam-files in `01_raw_alignments` being marked as duplicated (and thus deleted once the next step as finished). So if you want to be able to rerun without redoing the alignments you should be able to so by adding the  `--keep_intermediate_outputs` at the cost of using more disk space.

Otherwise you have to be more selective about what you delete. Hope that clears things up. :)

**Comment by biocyberman** [comment]
Thanks. It answered well my question. And in my opinion, it would be a good idea to especially keep the raw alignment no matter how `--keep_intermediate_outputs` is set, because it is the most time consuming step.
